In [28]:
import ast
import pandas as pd
import numpy as np
from scipy.special import softmax
from sklearn.metrics import roc_auc_score, average_precision_score

# DDI (wrt order)

|Order-->|2|3|4|4(unf)|5(unf)|6(unf)|7(unf)|
|---|---|---|---|---|---|---|---|
|N|500|500|20|
|Avg S (wrt gold)|2.11|2.07|4.64|
|% S>0 (wrt gold)|0.618|0.596|0.75|
|AUROC (wrt all)|0.6263|0.6276|0.5824|
|AUPRC (wrt all)|0.0055|0.0047|0.0678|
|Acc (wrt all)|0.0055|0.0060|0.1|||

unf : unfilitered, that is they are selected, without filtering for having their sublist in the record.

In [71]:

fdf = pd.read_json('../resultlogs/logger_logits_order_four_goldoffour_againstall_Qwen-Qwen2.5-7B-Instruct.jsonl', lines=True)
fdf['S'] = fdf['yes_logit'] - fdf['no_logit']
fdf.head()
print("Order= 4, N=", len(fdf[fdf.y == fdf.ygold]))
print("Avg S (wrt gold)", np.mean(fdf[fdf.y == fdf.ygold].S))
print("%S>0 (wrt gold)", sum(fdf[fdf.y == fdf.ygold].S > 0)/len(fdf[fdf.y == fdf.ygold]))

fdf["p_candidate"] = (
    fdf.groupby("line_id")["S"]
      .transform(lambda x: softmax(x.to_numpy()))
)

fdf["label"] = (fdf["y"] == fdf["ygold"]).astype(int)

auroc = roc_auc_score(fdf["label"], fdf["p_candidate"])
auprc = average_precision_score(fdf["label"], fdf["p_candidate"])
df_best = (
    fdf.loc[fdf.groupby("line_id")["p_candidate"].idxmax()]
      .reset_index(drop=True)
)

print(f"Accuracy: {len(df_best[df_best.y == df_best.ygold])/len(df_best):.4f}")

print(f"AUROC: {auroc:.4f}")
print(f"AUPRC: {auprc:.4f}")

Order= 4, N= 20
Avg S (wrt gold) 4.64609375
%S>0 (wrt gold) 0.75
Accuracy: 0.1000
AUROC: 0.5824
AUPRC: 0.0678

In [70]:
fdf = pd.read_json('../resultlogs/logger_logits_order_three_goldofthree_againstall_Qwen-Qwen2.5-7B-Instruct.jsonl', lines=True)
fdf['S'] = fdf['yes_logit'] - fdf['no_logit']
fdf.head()
print("Order= 3, N=", len(fdf[fdf.y == fdf.ygold]))
print("Avg S (wrt gold)", np.mean(fdf[fdf.y == fdf.ygold].S))
print("%S>0 (wrt gold)", sum(fdf[fdf.y == fdf.ygold].S > 0)/len(fdf[fdf.y == fdf.ygold]))

fdf["p_candidate"] = (
    fdf.groupby("line_id")["S"]
      .transform(lambda x: softmax(x.to_numpy()))
)

fdf["label"] = (fdf["y"] == fdf["ygold"]).astype(int)

auroc = roc_auc_score(fdf["label"], fdf["p_candidate"])
auprc = average_precision_score(fdf["label"], fdf["p_candidate"])
df_best = (
    fdf.loc[fdf.groupby("line_id")["p_candidate"].idxmax()]
      .reset_index(drop=True)
)

print(f"Accuracy: {len(df_best[df_best.y == df_best.ygold])/len(df_best):.4f}")

print(f"AUROC: {auroc:.4f}")
print(f"AUPRC: {auprc:.4f}")

Order= 3, N= 500
Avg S (wrt gold) 2.071296875
%S>0 (wrt gold) 0.596
Accuracy: 0.0060
AUROC: 0.6276
AUPRC: 0.0047

In [64]:
fdf.head()

,line_id,A,B,y,ygold,prompt,yes_logit,no_logit,p_yes,p_no,S,p_candidate,label
0,0,Acetylsalicylic acid,Apixaban,Peripheral arterial occlusive disease,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,23.984375,27.156250,0.040253,0.959961,-3.171875,2.562413e-10,0
1,0,Acetylsalicylic acid,Apixaban,Balance disorder,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,25.328125,25.250000,0.519531,0.480469,0.078125,6.608550e-09,0
2,0,Acetylsalicylic acid,Apixaban,Pain,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,22.859375,23.234375,0.407227,0.592773,-0.375000,4.200650e-09,0
3,0,Acetylsalicylic acid,Apixaban,Atrial fibrillation,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,21.640625,26.578125,0.007122,0.992676,-4.937500,4.383772e-11,0
4,0,Acetylsalicylic acid,Apixaban,Motor dysfunction,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,25.500000,24.250000,0.777344,0.222656,1.250000,2.133266e-08,0

0.016

In [69]:
fdf = pd.read_json('../resultlogs/logger_logits_order_two_goldoftwo_againstall_Qwen-Qwen2.5-7B-Instruct.jsonl', lines=True)
fdf['S'] = fdf['yes_logit'] - fdf['no_logit']
fdf.head()
print("Order= 2, N=", len(fdf[fdf.y == fdf.ygold]))
print("Avg S (wrt gold)", np.mean(fdf[fdf.y == fdf.ygold].S))
print("%S>0 (wrt gold)", sum(fdf[fdf.y == fdf.ygold].S > 0)/len(fdf[fdf.y == fdf.ygold]))

fdf["p_candidate"] = (
    fdf.groupby("line_id")["S"]
      .transform(lambda x: softmax(x.to_numpy()))
)

fdf["label"] = (fdf["y"] == fdf["ygold"]).astype(int)

auroc = roc_auc_score(fdf["label"], fdf["p_candidate"])
auprc = average_precision_score(fdf["label"], fdf["p_candidate"])

df_best = (
    fdf.loc[fdf.groupby("line_id")["p_candidate"].idxmax()]
      .reset_index(drop=True)
)

print(f"Accuracy: {len(df_best[df_best.y == df_best.ygold])/len(df_best):.4f}")
print(f"AUROC: {auroc:.4f}")
print(f"AUPRC: {auprc:.4f}")

Order= 2, N= 500
Avg S (wrt gold) 2.112953125
%S>0 (wrt gold) 0.618
Accuracy: 0.0160
AUROC: 0.6263
AUPRC: 0.0055

In [18]:
fdf

,line_id,A,B,y,ygold,prompt,yes_logit,no_logit,p_yes,p_no,S
0,0,Acetylsalicylic acid,Apixaban,Peripheral arterial occlusive disease,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,23.984375,27.156250,0.040253,0.959961,-3.171875
1,0,Acetylsalicylic acid,Apixaban,Balance disorder,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,25.328125,25.250000,0.519531,0.480469,0.078125
2,0,Acetylsalicylic acid,Apixaban,Pain,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,22.859375,23.234375,0.407227,0.592773,-0.375000
3,0,Acetylsalicylic acid,Apixaban,Atrial fibrillation,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,21.640625,26.578125,0.007122,0.992676,-4.937500
4,0,Acetylsalicylic acid,Apixaban,Motor dysfunction,Lower gastrointestinal haemorrhage,You are given a combination of drugs and a can...,25.500000,24.250000,0.777344,0.222656,1.250000
...,...,...,...,...,...,...,...,...,...,...,...
167995,499,Rivaroxaban,Acetylsalicylic acid,Drug-induced liver injury,Syncope,You are given a combination of drugs and a can...,30.468750,20.671875,1.000000,0.000056,9.796875
167996,499,Rivaroxaban,Acetylsalicylic acid,Blood magnesium decreased,Syncope,You are given a combination of drugs and a can...,18.703125,28.968750,0.000035,1.000000,-10.265625
167997,499,Rivaroxaban,Acetylsalicylic acid,Therapeutic response decreased,Syncope,You are given a combination of drugs and a can...,28.000000,22.734375,0.994629,0.005138,5.265625
167998,499,Rivaroxaban,Acetylsalicylic acid,psoriatic arthropathy,Syncope,You are given a combination of drugs and a can...,19.718750,28.062500,0.000238,1.000000,-8.343750
167999,499,Rivaroxaban,Acetylsalicylic acid,Overdose,Syncope,You are given a combination of drugs and a can...,22.625000,23.187500,0.363037,0.637207,-0.562500

,report_id,SE_above_0.9,DrugBankID,hyperedge_label,time,row_index,DrugBankID_sorted,len,slen
0,11809573,C0151878,"[DB01050, DB00555, DB00472, DB00273, DB00564, ...",1,2015Q4,1,"[DB00273, DB00472, DB00555, DB00557, DB00557, ...",7,6
1,20088990,C0435002,"[DB06605, DB00834, DB00695, DB00421, DB00999, ...",1,2021Q4,2,"[DB00264, DB00331, DB00413, DB00421, DB00695, ...",9,9
2,11703282,C0235431,"[DB01118, DB06228, DB01118, DB00177, DB00612, ...",1,2015Q4,3,"[DB00177, DB00575, DB00612, DB01118, DB01118, ...",7,6
3,14916073,C0853141,"[DB00341, DB00588]",1,2018Q2,4,"[DB00341, DB00588]",2,2
4,20172173,C0699828,"[DB01149, DB00656]",1,2021Q4,5,"[DB00656, DB01149]",2,2

In [79]:
df = pd.read_csv('../../HODDI/dataset/HODDI_v1/dictionary/Drugbank_ID_SMILE_all_structure links.csv')
drugid2drugname = dict(zip(df["DrugBank ID"].values, df["Name"].values ))

maindf = pd.read_csv("../../HODDI/dataset/HODDI_v1/HODDI/Merged_Dataset/pos.csv")
maindf["DrugBankID"] = maindf["DrugBankID"].apply(ast.literal_eval)
maindf["DrugBankID_sorted"] = [sorted(dbl) for dbl in maindf["DrugBankID"].values]
drug_lists = maindf["DrugBankID"].values
side_effect_list = maindf["SE_above_0.9"].values
maindf["len"] = [len(dl) for dl in maindf.DrugBankID_sorted.values]
maindf["slen"] = [len(set(dl)) for dl in maindf.DrugBankID_sorted.values]
maindf.head()


ORDER = 10
subdf = maindf[(maindf.len == ORDER) & (maindf.slen == ORDER)]
subdf

mask = []
for dl in subdf.DrugBankID_sorted.values:
    flag = 1
    for d in dl:
        if d not in drugid2drugname:
            flag = 0
            break
    if flag == 1:
        mask.append(True)
    else:
        mask.append(False)

print(len(subdf), len(subdf[mask]), len(set(subdf[mask]["SE_above_0.9"].values)))

fp = open(f"../data/{ORDER}-list-unfiltered.txt", "w")
for i in subdf[mask].index.values:
    print(i, file=fp)
fp.close()

subdf[mask]

2588 2123 908

,report_id,SE_above_0.9,DrugBankID,hyperedge_label,time,row_index,DrugBankID_sorted,len,slen
25,12965424,C0919671,"[DB00313, DB00502, DB09287, DB01914, DB01390, ...",1,2016Q4,26,"[DB00213, DB00313, DB00363, DB00502, DB00612, ...",10,10
124,12510191,C1527311,"[DB01175, DB01129, DB01222, DB00983, DB06605, ...",1,2016Q4,125,"[DB00277, DB00471, DB00695, DB00966, DB00983, ...",10,10
178,11584681,C0085580,"[DB00387, DB00230, DB00734, DB00829, DB00695, ...",1,2015Q4,179,"[DB00186, DB00230, DB00313, DB00370, DB00387, ...",10,10
179,14381475,C0426732,"[DB00678, DB00451, DB00335, DB06724, DB11094, ...",1,2021Q2,180,"[DB00136, DB00331, DB00335, DB00381, DB00451, ...",10,10
201,13005738,C0085639,"[DB00879, DB00625, DB14126, DB00999, DB01050, ...",1,2016Q4,202,"[DB00245, DB00334, DB00381, DB00502, DB00625, ...",10,10
...,...,...,...,...,...,...,...,...,...
110742,19491099,C3160741,"[DB00434, DB00653, DB01156, DB00327, DB00202, ...",1,2021Q3,110743,"[DB00186, DB00202, DB00292, DB00327, DB00434, ...",10,10
110753,9835566,C0018418,"[DB00331, DB01261, DB00404, DB01104, DB00999, ...",1,2015Q1,110754,"[DB00264, DB00331, DB00381, DB00384, DB00404, ...",10,10
110756,15777822,C0015397,"[DB14513, DB00722, DB00540, DB00588, DB11075, ...",1,2018Q4,110757,"[DB00476, DB00540, DB00588, DB00654, DB00722, ...",10,10
110864,12537120,C0575081,"[DB00196, DB01015, DB00440, DB06218, DB00555, ...",1,2016Q3,110865,"[DB00196, DB00300, DB00440, DB00503, DB00555, ...",10,10
110936,19439546,C0018790,"[DB01115, DB01164, DB00067, DB00368, DB00668, ...",1,2021Q2,110937,"[DB00067, DB00149, DB00368, DB00668, DB01115, ...",10,10

8061 6786

,report_id,SE_above_0.9,DrugBankID,hyperedge_label,time,row_index,DrugBankID_sorted,len,slen
0,11809573,C0151878,"[DB01050, DB00555, DB00472, DB00273, DB00564, ...",1,2015Q4,1,"[DB00273, DB00472, DB00555, DB00557, DB00557, ...",7,6
1,20088990,C0435002,"[DB06605, DB00834, DB00695, DB00421, DB00999, ...",1,2021Q4,2,"[DB00264, DB00331, DB00413, DB00421, DB00695, ...",9,9
2,11703282,C0235431,"[DB01118, DB06228, DB01118, DB00177, DB00612, ...",1,2015Q4,3,"[DB00177, DB00575, DB00612, DB01118, DB01118, ...",7,6
3,14916073,C0853141,"[DB00341, DB00588]",1,2018Q2,4,"[DB00341, DB00588]",2,2
4,20172173,C0699828,"[DB01149, DB00656]",1,2021Q4,5,"[DB00656, DB01149]",2,2
...,...,...,...,...,...,...,...,...,...
111067,22783711,C3160741,"[DB00472, DB00150]",1,2023Q3,111068,"[DB00150, DB00472]",2,2
111068,13490107,C1443060,"[DB00776, DB00904, DB01174, DB00904]",1,2017Q2,111069,"[DB00776, DB00904, DB00904, DB01174]",4,3
111069,15109894,C0012817,"[DB00437, DB00047, DB13919, DB08816, DB00381, ...",1,2018Q3,111070,"[DB00047, DB00331, DB00338, DB00381, DB00437, ...",13,12
111070,16811816,C0751494,"[DB13919, DB00528, DB01065]",1,2019Q3,111071,"[DB00528, DB01065, DB13919]",3,3
111071,14758667,C0017181,"[DB01327, DB01045]",1,2018Q2,111072,"[DB01045, DB01327]",2,2